const apiConfig = window.ROUTEBOARD_SUPABASE;
const api = `${apiConfig.url}/rest/v1/deliveries`;
const pickupsApi = `${apiConfig.url}/rest/v1/pickup_deliveries`;
const headers = { apikey: apiConfig.anonKey, Authorization: `Bearer ${apiConfig.anonKey}`, 'Content-Type': 'application/json' };
let deliveries = [];
let pickups = JSON.parse(localStorage.getItem('routeboard-pickups')) || [];

const escapeHtml = (value) => String(value ?? '').replace(/[&<>'"]/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[character]));
const tubsLabel = (value) => `${value} ${value === 1 ? 'tub' : 'tubs'}`;
async function request(base, path = '', options = {}) { const response = await fetch(`${base}${path}`, { ...options, headers: { ...headers, ...(options.headers || {}) } }); if (!response.ok) throw new Error(`Request failed (${response.status})`); return response.status === 204 ? null : response.json(); }
async function loadDeliveries() { try { deliveries = await request(api, '?select=id,customer,address,phone,area,tubs,completed,completed_at,stop_order&order=stop_order.asc'); } catch { deliveries = JSON.parse(localStorage.getItem('routeboard-deliveries')) || []; } render(); }
async function loadPickups() { const localPickups = JSON.parse(localStorage.getItem('routeboard-pickups')) || []; try { pickups = await request(pickupsApi, '?select=id,customer,address,phone,area,tubs,completed,completed_at,stop_order&order=stop_order.asc'); if (!pickups.length && localPickups.length) { pickups = await request(pickupsApi, '', { method: 'POST', headers: { Prefer: 'return=representation' }, body: JSON.stringify(localPickups) }); localStorage.removeItem('routeboard-pickups'); } } catch { pickups = localPickups; } render(); }
function updateMeter(items, percentId, progressId, statusId, label) { const complete = items.filter((item) => item.completed).length; const percent = items.length ? Math.round(complete / items.length * 100) : 0; document.querySelector(`#${percentId}`).textContent = `${percent}%`; document.querySelector(`#${progressId}`).style.width = `${percent}%`; document.querySelector(`#${statusId}`).textContent = items.length ? `${complete} of ${items.length} ${label} complete` : `No ${label} loaded`; }
function render() { updateMeter(deliveries, 'overview-percent', 'overview-progress', 'overview-route-status', 'deliveries'); updateMeter(pickups, 'pickup-percent', 'pickup-progress', 'pickup-route-status', 'pick ups'); renderDeliveries(); renderPickups(); }
function renderDeliveries() { document.querySelector('#delivery-list').innerHTML = deliveries.length ? deliveries.map((delivery, index) => `<article class="delivery-card ${delivery.completed ? 'completed' : ''}"><span class="stop-number">${String(index + 1).padStart(2, '0')}</span><div class="delivery-info"><strong>${escapeHtml(delivery.customer)}</strong><span>${escapeHtml(delivery.address)}${delivery.phone ? ` · ${escapeHtml(delivery.phone)}` : ''}</span><div class="delivery-actions"><b>${tubsLabel(Number(delivery.tubs || 0))}</b>${delivery.phone ? `<a class="contact-link" href="tel:${escapeHtml(delivery.phone)}">Call</a>` : ''}<a class="contact-link" target="_blank" rel="noopener" href="https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(delivery.address || '')}">Google Maps</a></div></div><button class="complete-button ${delivery.completed ? 'done' : ''}" data-id="${escapeHtml(delivery.id)}">${delivery.completed ? 'Completed' : 'Mark complete'}</button></article>`).join('') : '<div class="empty-state">No deliveries yet. Import a CSV to get started.</div>'; document.querySelectorAll('#delivery-list .complete-button').forEach((button) => button.addEventListener('click', () => toggleDelivery(button.dataset.id))); }
function renderPickups() { document.querySelector('#pickup-list').innerHTML = pickups.length ? pickups.map((pickup, index) => `<article class="delivery-card ${pickup.completed ? 'completed' : ''}"><span class="stop-number">${String(index + 1).padStart(2, '0')}</span><div class="delivery-info"><strong>${escapeHtml(pickup.customer)}</strong><span>Order #${escapeHtml(pickup.order_number || '')}${pickup.phone ? ` · ${escapeHtml(pickup.phone)}` : ''}</span><div class="delivery-actions"><b>${tubsLabel(Number(pickup.tubs || 0))}</b>${pickup.phone ? `<a class="contact-link" href="tel:${escapeHtml(pickup.phone)}">Call</a>` : ''}</div></div><button class="complete-button ${pickup.completed ? 'done' : ''}" data-pickup-id="${escapeHtml(pickup.id)}">${pickup.completed ? 'Completed' : 'Mark complete'}</button></article>`).join('') : '<div class="empty-state">No pick ups yet. Import a CSV to get started.</div>'; document.querySelectorAll('#pickup-list .complete-button').forEach((button) => button.addEventListener('click', () => togglePickup(button.dataset.pickupId))); }
async function addDelivery(form, delivery = null) { const fields = delivery || Object.fromEntries(new FormData(form)); const item = { id: delivery?.id || `MANUAL-${Date.now()}`, customer: fields.customer, address: fields.address, phone: fields.phone || '', area: fields.area || '', tubs: Number(fields.tubs), completed: false, stop_order: deliveries.length }; try { const saved = await request(api, '', { method: 'POST', headers: { Prefer: 'return=representation' }, body: JSON.stringify(item) }); deliveries.push(saved[0] || item); } catch { deliveries.push(item); localStorage.setItem('routeboard-deliveries', JSON.stringify(deliveries)); } if (form) { form.reset(); form.hidden = true; } render(); }
async function addPickup(form, pickup = null) { const item = pickup || { id: `PICKUP-${Date.now()}`, customer: '', address: '', phone: '', tubs: 0, completed: false, stop_order: pickups.length }; try { const saved = await request(pickupsApi, '', { method: 'POST', headers: { Prefer: 'return=representation' }, body: JSON.stringify(item) }); pickups.push(saved[0] || item); } catch { pickups.push(item); localStorage.setItem('routeboard-pickups', JSON.stringify(pickups)); } if (form) { form.reset(); form.hidden = true; } render(); }
async function toggleDelivery(id) { const delivery = deliveries.find((item) => item.id === id); if (!delivery) return; delivery.completed = !delivery.completed; try { await request(api, `?id=eq.${encodeURIComponent(id)}`, { method: 'PATCH', headers: { Prefer: 'return=minimal' }, body: JSON.stringify({ completed: delivery.completed, completed_at: delivery.completed ? new Date().toISOString() : null }) }); } catch { localStorage.setItem('routeboard-deliveries', JSON.stringify(deliveries)); } render(); }
async function togglePickup(id) { const pickup = pickups.find((item) => item.id === id); if (!pickup) return; pickup.completed = !pickup.completed; try { await request(pickupsApi, `?id=eq.${encodeURIComponent(id)}`, { method: 'PATCH', headers: { Prefer: 'return=minimal' }, body: JSON.stringify({ completed: pickup.completed, completed_at: pickup.completed ? new Date().toISOString() : null }) }); } catch { localStorage.setItem('routeboard-pickups', JSON.stringify(pickups)); } render(); }
async function importCsv(file, replace = false) { try { const rows = parseCsv(await file.text()); const [header, ...data] = rows; const columns = header.map((column) => column.toLowerCase()); const required = ['customer', 'address', 'tubs']; if (!required.every((column) => columns.includes(column))) { window.alert('CSV must include customer, address, and tubs columns.'); return; } const imported = data.filter((row) => row.length).map((row) => Object.fromEntries(columns.map((column, index) => [column, row[index] || '']))).filter((item) => item.customer && item.address && Number(item.tubs) > 0); if (imported.length === 0) { window.alert('No valid deliveries found in CSV.'); return; } if (replace && deliveries.length > 0) { const confirmed = window.confirm(`Replace ${deliveries.length} existing deliveries with ${imported.length} new ones?`); if (!confirmed) return; deliveries = []; } for (const item of imported) await addDelivery(null, item); window.alert(`Successfully imported ${imported.length} deliveries!`); } catch (error) { window.alert(`Error importing CSV: ${error.message}`); } }
async function importPickupsCsv(file, replace = false) { try { const rows = parseCsv(await file.text()); const [header, ...data] = rows; const columns = header.map((column) => column.toLowerCase()); const required = ['name', 'tubs']; if (!required.every((column) => columns.includes(column))) { window.alert('CSV must include name and tubs columns.'); return; } const imported = data.filter((row) => row.length).map((row) => Object.fromEntries(columns.map((column, index) => [column, row[index] || '']))).filter((item) => item.name && Number(item.tubs) > 0); if (imported.length === 0) { window.alert('No valid pick ups found in CSV.'); return; } if (replace && pickups.length > 0) { const confirmed = window.confirm(`Replace ${pickups.length} existing pick ups with ${imported.length} new ones?`); if (!confirmed) return; pickups = []; } for (const item of imported) { const pickup = { id: `PICKUP-${Date.now()}-${Math.random()}`, customer: item.name, address: '', order_number: item.order_number || '', phone: item.phone || '', tubs: Number(item.tubs), completed: false, stop_order: pickups.length }; await addPickup(null, pickup); } window.alert(`Successfully imported ${imported.length} pick ups!`); } catch (error) { window.alert(`Error importing CSV: ${error.message}`); } }
function parseCsv(text) { const rows = []; let row = []; let value = ''; let quoted = false; for (let index = 0; index < text.length; index += 1) { const character = text[index]; const next = text[index + 1]; if (character === '"' && quoted && next === '"') { value += '"'; index += 1; } else if (character === '"') quoted = !quoted; else if (character === ',' && !quoted) { row.push(value.trim()); value = ''; } else if ((character === '\n' || character === '\r') && !quoted) { if (character === '\r' && next === '\n') index += 1; row.push(value.trim()); if (row.some(Boolean)) rows.push(row); row = []; value = ''; } else value += character; } if (value || row.length) { row.push(value.trim()); rows.push(row); } return rows; }
function clearAllDeliveries() { if (deliveries.length === 0) { window.alert('No deliveries to clear.'); return; } const confirmed = window.confirm(`Clear all ${deliveries.length} deliveries? This cannot be undone.`); if (!confirmed) return; deliveries = []; localStorage.removeItem('routeboard-deliveries'); render(); }
function clearAllPickups() { if (pickups.length === 0) { window.alert('No pick ups to clear.'); return; } const confirmed = window.confirm(`Clear all ${pickups.length} pick ups? This cannot be undone.`); if (!confirmed) return; pickups = []; localStorage.removeItem('routeboard-pickups'); render(); }
function switchTab(tabName) { document.querySelectorAll('.section').forEach(section => section.classList.remove('active-section')); document.querySelectorAll('.tab-button').forEach(button => button.classList.remove('active')); document.querySelector(`#${tabName}`).classList.add('active-section'); document.querySelector(`[data-tab="${tabName}"]`).classList.add('active'); }
document.querySelectorAll('.tab-button').forEach(button => button.addEventListener('click', () => switchTab(button.dataset.tab)));
document.querySelector('#delivery-csv').addEventListener('click', (event) => { event.currentTarget.value = ''; });
document.querySelector('#delivery-csv').addEventListener('change', (event) => { if (event.target.files[0]) importCsv(event.target.files[0], false); });
document.querySelector('#pickup-csv').addEventListener('click', (event) => { event.currentTarget.value = ''; });
document.querySelector('#pickup-csv').addEventListener('change', (event) => { if (event.target.files[0]) importPickupsCsv(event.target.files[0], false); });
document.querySelector('#delivery-clear-btn').addEventListener('click', clearAllDeliveries);
document.querySelector('#pickup-clear-btn').addEventListener('click', clearAllPickups);
document.querySelector('#role-select').addEventListener('change', (event) => { document.querySelector('.eyebrow').textContent = `${event.target.value} view`; });
loadDeliveries();
loadPickups();
